import type { CompanySeed } from "@/lib/types";

export const companyCatalog: CompanySeed[] = [
  {
    name: "Apple",
    slug: "apple",
    provider: "public_page",
    status: "public-page-monitor",
    homepage: "https://jobs.apple.com",
    sourceUrl: "https://jobs.apple.com/en-us/search",
    notes: "No documented public API found; monitor only if terms and robots allow.",
    priority: 100,
    enabled: false,
  },
  {
    name: "Meta",
    slug: "meta",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://www.metacareers.com/jobs",
    notes: "No compliant public jobs API confirmed yet.",
    priority: 99,
    enabled: false,
  },
  {
    name: "Netflix",
    slug: "netflix",
    provider: "public_page",
    status: "public-page-monitor",
    homepage: "https://jobs.netflix.com",
    sourceUrl: "https://explore.jobs.netflix.net/careers",
    notes: "Public structured careers site, but no documented public API confirmed.",
    priority: 98,
    enabled: false,
  },
  {
    name: "Google",
    slug: "google",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://www.google.com/about/careers/applications/jobs/results",
    notes: "No public Google Careers extraction API confirmed.",
    priority: 97,
    enabled: false,
  },
  {
    name: "OpenAI",
    slug: "openai",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://openai.com/careers",
    priority: 96,
    enabled: true,
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    provider: "ashby",
    status: "needs-confirmation",
    homepage: "https://www.anthropic.com/careers",
    priority: 95,
    enabled: true,
  },
  {
    name: "Vercel",
    slug: "vercel",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://vercel.com/careers",
    priority: 94,
    enabled: true,
  },
  {
    name: "Stripe",
    slug: "stripe",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://stripe.com/jobs",
    priority: 93,
    enabled: true,
  },
  {
    name: "Figma",
    slug: "figma",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://www.figma.com/careers",
    priority: 92,
    enabled: true,
  },
  {
    name: "Notion",
    slug: "notion",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://www.notion.com/careers",
    priority: 91,
    enabled: true,
  },
  {
    name: "Reddit",
    slug: "reddit",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://www.redditinc.com/careers",
    priority: 90,
    enabled: true,
  },
  {
    name: "Discord",
    slug: "discord",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://discord.com/jobs",
    priority: 89,
    enabled: true,
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://www.coinbase.com/careers",
    priority: 88,
    enabled: true,
  },
  {
    name: "Databricks",
    slug: "databricks",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://www.databricks.com/company/careers",
    priority: 87,
    enabled: true,
  },
  {
    name: "Ramp",
    slug: "ramp",
    provider: "ashby",
    status: "needs-confirmation",
    homepage: "https://ramp.com/careers",
    priority: 86,
    enabled: true,
  },
  {
    name: "Rippling",
    slug: "rippling",
    provider: "ashby",
    status: "needs-confirmation",
    homepage: "https://www.rippling.com/careers",
    priority: 85,
    enabled: true,
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://jobs.careers.microsoft.com",
    notes: "Needs a confirmed free public source before polling.",
    priority: 84,
    enabled: false,
  },
  {
    name: "Amazon",
    slug: "amazon",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://www.amazon.jobs",
    notes: "Needs a confirmed free public source before polling.",
    priority: 83,
    enabled: false,
  },
  {
    name: "Nvidia",
    slug: "nvidia",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://www.nvidia.com/en-us/about-nvidia/careers",
    notes: "Needs a confirmed free public source before polling.",
    priority: 82,
    enabled: false,
  },
  {
    name: "Snowflake",
    slug: "snowflake",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://careers.snowflake.com",
    notes: "Needs a confirmed free public source before polling.",
    priority: 81,
    enabled: false,
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://careers.airbnb.com",
    priority: 80,
    enabled: true,
  },
  {
    name: "Uber",
    slug: "uber",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://www.uber.com/us/en/careers",
    notes: "Needs a confirmed free public source before polling.",
    priority: 79,
    enabled: false,
  },
  {
    name: "DoorDash",
    slug: "doordashusa",
    provider: "greenhouse",
    status: "needs-confirmation",
    homepage: "https://careers.doordash.com",
    priority: 78,
    enabled: true,
  },
  {
    name: "Roblox",
    slug: "roblox",
    provider: "unsupported",
    status: "unsupported",
    homepage: "https://careers.roblox.com",
    notes: "Needs a confirmed free public source before polling.",
    priority: 77,
    enabled: false,
  },
];
